/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.youri.view;

import io.youri.control.Functions;
import java.awt.Color;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author YODI YANWAR
 */
public class FormKotaKab extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManajemenLokasi
     */
    
    public Functions fungsi;
    
    public FormKotaKab() {
        getContentPane().setBackground(Color.WHITE);
        initComponents();        
        inisialisasi();
        load();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerKotaKab = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNamaKotaKab = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        labelKotaKab = new javax.swing.JLabel();
        labelTitikDuaId1 = new javax.swing.JLabel();
        comboKotaKab = new javax.swing.JComboBox();
        labelId = new javax.swing.JLabel();
        buttonTutup = new javax.swing.JButton();
        layerDaftar = new javax.swing.JLayeredPane();
        labelCari = new javax.swing.JLabel();
        textCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKotaKab = new javax.swing.JTable();

        layerKotaKab.setBorder(javax.swing.BorderFactory.createTitledBorder("Kota / Kabupaten"));

        jLabel3.setText("Nama Kota / Kabupaten");

        jLabel4.setText(":");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        labelKotaKab.setText("Kota / Kab");

        labelTitikDuaId1.setText(":");

        comboKotaKab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kota", "Kab" }));

        javax.swing.GroupLayout layerKotaKabLayout = new javax.swing.GroupLayout(layerKotaKab);
        layerKotaKab.setLayout(layerKotaKabLayout);
        layerKotaKabLayout.setHorizontalGroup(
            layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerKotaKabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerKotaKabLayout.createSequentialGroup()
                        .addComponent(labelKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTitikDuaId1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layerKotaKabLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNamaKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layerKotaKabLayout.createSequentialGroup()
                                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerKotaKabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layerKotaKabLayout.setVerticalGroup(
            layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerKotaKabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitikDuaId1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layerKotaKabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layerKotaKab.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(textNamaKotaKab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(buttonSimpan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(buttonHapus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(buttonBatal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(labelKotaKab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(labelTitikDuaId1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(comboKotaKab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerKotaKab.setLayer(labelId, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonTutup.setText("Tutup");
        buttonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTutupActionPerformed(evt);
            }
        });

        layerDaftar.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Kota / Kabupaten"));

        labelCari.setText("Cari Berdasar Nama Kota / Kabupaten    :");

        textCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCariKeyTyped(evt);
            }
        });

        tableKotaKab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKotaKab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKotaKabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKotaKab);

        javax.swing.GroupLayout layerDaftarLayout = new javax.swing.GroupLayout(layerDaftar);
        layerDaftar.setLayout(layerDaftarLayout);
        layerDaftarLayout.setHorizontalGroup(
            layerDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCari, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layerDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layerDaftarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layerDaftarLayout.setVerticalGroup(
            layerDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerDaftarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layerDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layerDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layerDaftarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGap(50, 50, 50)))
        );
        layerDaftar.setLayer(labelCari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerDaftar.setLayer(textCari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerDaftar.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(layerKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(layerDaftar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(layerKotaKab)
                    .addComponent(layerDaftar))
                .addGap(10, 10, 10)
                .addComponent(buttonTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        edit();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        hapus();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        batal();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void tableKotaKabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKotaKabMouseClicked
        klikTable();
    }//GEN-LAST:event_tableKotaKabMouseClicked

    private void buttonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTutupActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonTutupActionPerformed

    private void textCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCariKeyTyped
        cari();
    }//GEN-LAST:event_textCariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTutup;
    private javax.swing.JComboBox comboKotaKab;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelKotaKab;
    private javax.swing.JLabel labelTitikDuaId1;
    private javax.swing.JLayeredPane layerDaftar;
    private javax.swing.JLayeredPane layerKotaKab;
    private javax.swing.JTable tableKotaKab;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textNamaKotaKab;
    // End of variables declaration//GEN-END:variables

    private void inisialisasi() {
        buttonEdit.setVisible(false);
        buttonHapus.setVisible(false);
        buttonSimpan.setText("Baru");
        buttonBatal.setVisible(false);
        comboKotaKab.setEnabled(false);
        labelId.setVisible(false);
        
        setTextStatus(false);
    }

    private void load() {
        fungsi = new Functions();
        
        String sql = "SELECT id_kota_kab AS 'ID', "
                + "kota_or_kab AS 'Kota / Kab',"
                + "nama_kota_kab AS 'Nama Kota / Kabupaten' "
                + "FROM tbl_kota_kab";
        
        fungsi.bindingTable(sql, tableKotaKab);       
    }

    private void cari() {
        fungsi = new Functions();
            
        String sql = "SELECT id_kota_kab AS 'ID', "
                + "kota_or_kab AS 'Kota / Kab',"
                + "nama_kota_kab AS 'Nama Kota / Kabupaten' "
                + "FROM tbl_kota_kab "
                + "WHERE nama_kota_kab "
                + "LIKE '%"+textCari.getText()+"%'";
        
        fungsi.bindingTable(sql, tableKotaKab);         
    }
    
    private void setTextStatus(boolean status){
        textNamaKotaKab.setEnabled(status);
    }

    private void simpan() {
        if("Baru".equals(buttonSimpan.getText())){
            setTextStatus(true);
            buttonSimpan.setText("Simpan");
            buttonBatal.setVisible(true);
            comboKotaKab.setEnabled(true);
            
        }else
        if("Simpan".equals(buttonSimpan.getText())){
            
            Date wktInput = new Date();
            Timestamp ts = new Timestamp(wktInput.getTime());
            
            String sql = "INSERT INTO `tbl_kota_kab`(`kota_or_kab`, `nama_kota_kab`) "
                    + "VALUES ('"+comboKotaKab.getSelectedItem()+"','"+textNamaKotaKab.getText()+"')";
            
            if(fungsi.runSQL(sql)){
                fungsi.msgBox("Berhasil Menambah Data Lokasi", "SUKSES", 1);
                buttonSimpan.setText("Baru");
                clear();
                setTextStatus(false);
                buttonBatal.setVisible(false);
                comboKotaKab.setEnabled(false);
            load();
            } else{
                fungsi.msgBox("Gagal Menambah Data Lokasi", "GAGAL", 0);
            }
        }
    }

    private void clear() {
        textCari.setText("");
        textNamaKotaKab.setText("");
        labelId.setText("");
    }

    private void klikTable() {
        
        buttonEdit.setVisible(true);
        buttonHapus.setVisible(true);
        buttonBatal.setVisible(true);
        buttonSimpan.setVisible(false);
        comboKotaKab.setEnabled(true);
        setTextStatus(true);
        
       int i=this.tableKotaKab.getSelectedRow();
        if(i==-1)
        {
            return;
        }
       
       labelId.setText(String.valueOf(tableKotaKab.getModel().getValueAt(i,0)));
       comboKotaKab.setSelectedItem(String.valueOf(tableKotaKab.getModel().getValueAt(i,1)));
       textNamaKotaKab.setText((String)tableKotaKab.getModel().getValueAt(i,2));
    }

    private void batal() {
            clear();
            buttonEdit.setVisible(false);
            buttonHapus.setVisible(false);
            buttonSimpan.setText("Baru");
            buttonSimpan.setVisible(true);
            setTextStatus(false);     
            buttonBatal.setVisible(false);
            comboKotaKab.setEnabled(false);
    }

    private void edit() {
        
            Date wktInput = new Date();
            Timestamp ts = new Timestamp(wktInput.getTime());
            
        String sql = "UPDATE `tbl_kota_kab` "
                + "SET `kota_or_kab`='"+comboKotaKab.getSelectedItem()+"',"
                + "`nama_kota_kab`='"+textNamaKotaKab.getText()+"' "
                + "WHERE `id_kota_kab`='"+labelId.getText()+"'";
        
            if(fungsi.runSQL(sql)){
                fungsi.msgBox("Berhasil Mengubah Data Lokasi", "SUKSES", 1);
                buttonSimpan.setVisible(true);
                buttonSimpan.setText("Baru");
                buttonEdit.setVisible(false);
                buttonHapus.setVisible(false);
                clear();
                setTextStatus(false);
                comboKotaKab.setEnabled(false);
                buttonBatal.setVisible(false);
            load();
            } else{
                fungsi.msgBox("Gagal Mengubah Data Lokasi", "GAGAL", 0);
            }        
    }

    private void hapus() {
        int app;
        if((app = JOptionPane.showConfirmDialog(null,"Hapus Data Pasien ?","Perhatian",JOptionPane.YES_NO_OPTION))==0){
             String sql = "DELETE FROM `tbl_kota_kab` WHERE id_kota_kab='"+labelId.getText()+"'";
             
            if(fungsi.runSQL(sql)){
                fungsi.msgBox("Berhasil Manghapus Data Lokasi", "SUKSES", 1);
                buttonSimpan.setVisible(true);
                buttonSimpan.setText("Baru");
                buttonEdit.setVisible(false);
                buttonHapus.setVisible(false);
                clear();
                setTextStatus(false);
                buttonBatal.setVisible(false);
                comboKotaKab.setEnabled(false);
            load();
            } else{
                fungsi.msgBox("Gagal Manghapus Data Lokasi", "GAGAL", 0);
            }               
        }           
    }
    
}
