/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.youri.view;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author YODI YANWAR
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    FormLogin formLogin = new FormLogin();
    //private FormUser formUser;
    
    public MainMenu() {
        
    }
    
    public MainMenu(int id_kategori_user,String kategoriUser, String namaUser){
        initComponents();
        
        if("Administrator".equals(kategoriUser)){
            menuAdministrasi.setVisible(false);
            menuLaporan.setVisible(false);
            
        }else
        if("Administrasi".equals(kategoriUser)){
            menuUser.setVisible(false);
            
        }        
        
        
        setExtendedState(MainMenu.MAXIMIZED_BOTH);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        MenuBarUtama = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuItemUser = new javax.swing.JMenuItem();
        menuItemKategoriUser = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        menuAdministrasi = new javax.swing.JMenu();
        menuLaporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1323, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });

        menuItemUser.setText("Manajemen User");
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        menuUser.add(menuItemUser);

        menuItemKategoriUser.setText("Manajemen Kategori User");
        menuUser.add(menuItemKategoriUser);

        MenuBarUtama.add(menuUser);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });

        menuItemExit.setText("Keluar");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuExit.add(menuItemExit);

        MenuBarUtama.add(menuExit);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });

        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuLogout.add(menuItemLogout);

        MenuBarUtama.add(menuLogout);

        menuAdministrasi.setText("Administrasi");
        MenuBarUtama.add(menuAdministrasi);

        menuLaporan.setText("Laporan");
        MenuBarUtama.add(menuLaporan);

        setJMenuBar(MenuBarUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        int app;
        if((app = JOptionPane.showConfirmDialog(null,"Tutup Program ?","Perhatian",JOptionPane.YES_NO_OPTION))==0){
             System.exit(0);
        }   
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        this.dispose();
        formLogin.setVisible(true);
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed

    }//GEN-LAST:event_menuUserActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        
     
        //FormUser formUser = null;
        
        //if(formUser == null){
            FormUser formUser = new FormUser();
            this.desktopPane.add(formUser);
            formUser.show();            
        //}
        
            System.out.println(formUser);
    }//GEN-LAST:event_menuItemUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarUtama;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu menuAdministrasi;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemKategoriUser;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
